set_property PACKAGE_PIN L16 [get_ports CLK]
set_property PACKAGE_PIN D18 [get_ports {LED[3]}]
set_property PACKAGE_PIN G14 [get_ports {LED[2]}]
set_property PACKAGE_PIN M15 [get_ports {LED[1]}]
set_property PACKAGE_PIN M14 [get_ports {LED[0]}]

set_property PACKAGE_PIN Y16 [get_ports RST]

set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports RST]

create_clock -period 8.000 -name sys_clk_pin -waveform {0.000 4.000} -add [get_ports CLK]

set_property IOSTANDARD LVCMOS33 [get_ports BTN0]
set_property IOSTANDARD LVCMOS33 [get_ports MOTOR_DIR1]
set_property IOSTANDARD LVCMOS33 [get_ports MOTOR_EN1]
set_property IOSTANDARD LVCMOS33 [get_ports SW0]
set_property PACKAGE_PIN R18 [get_ports BTN0]
set_property PACKAGE_PIN G15 [get_ports SW0]
set_property PACKAGE_PIN T20 [get_ports MOTOR_EN1]
set_property PACKAGE_PIN U20 [get_ports MOTOR_DIR1]

set_property PACKAGE_PIN Y18 [get_ports MOTOR_EN2]
set_property PACKAGE_PIN Y19 [get_ports MOTOR_DIR2]
set_property IOSTANDARD LVCMOS33 [get_ports MOTOR_DIR2]
set_property IOSTANDARD LVCMOS33 [get_ports MOTOR_EN2]
